name: Build and Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone the project
        uses: actions/checkout@v3
      - name: Install the software
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Removes any previously compiled files and artifacts
        run: mvn clean
      - name: Run unit tests
        run: mvn test
      - name: Package code
        run: mvn package
